export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const CLEAR_USER = "CLEAR_USER";
export const ERRORS = "ERRORS";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const TOGGLE_CART_ITEM = "TOGGLE_CART_ITEM";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const REDUCE_ITEM_FROM_CART = "REDUCE_ITEM_FROM_CART";
